apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: docker.io/your-dockerhub-username/house-price-model:latest  # Overwritten by pipeline
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://house-price-api-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
